name: Build
on:
  push:
    branches: [ build ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Short SHA1 from git commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Prepare Go packages
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.3'
      - name: Build
        run: go mod tidy && CGO_ENABLED=0 go build -a
      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/newbiediver/default-backend
          tags: |
            latest
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Notify to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "build"
          payload: |
            {
              "text": "`Build result from Github Actions Runner`",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "`Build result from Github Actions Runner`"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Built repository ${{ github.repository }}.*\nWorkflow: ${{ github.workflow }}\nPlatform: ${{ runner.os }}\nResult: *${{ job.status }}*"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://common.kdev.pro/files/images/${{ job.status }}.png",
                    "alt_text": "result thumbnail"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*ID: ${{ github.run_id }}\n*Build No: #${{ github.run_number }}\n*Repo: ${{ github.server_url }}/${{ github.repository }}\n*Branch: ${{ github.ref_name }}\n*Revision: ${{ steps.vars.outputs.sha_short }}\n*Message: ${{ github.event.head_commit.message }}"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()